server:
  port: 9090

#设置网关地址,设置过滤条件未/api/auth,需要在其中指定服务中心server-center的端口
spring:
  cloud:
    gateway:
      routes:
       - id: server-auth
         uri: lb://server-auth
         order: 9091
         predicates:
         - Path=/api/auth/**
         filters:
         - StripPrefix=2




